import "../styles/globals.css";
import {
  Container,
  AppBar,
  Toolbar,
  Typography,
  Box,
  Button,
} from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import SideBar from "../components/Sidebar";
import TopBar from "../components/TopBar";
import { DataProvider } from "../contexts/DataContext";
import { FilterProvider } from "../contexts/FilterContext";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: "flex" }}>
        <TopBar />
        <SideBar />
        <DataProvider>
          <FilterProvider>
            <Component {...pageProps} />
          </FilterProvider>
        </DataProvider>
      </Box>
    </>
  );
}

export default MyApp;
